### PR TITLE
Wrapped key up model update in an option to preserve original behavio…

### PR DESCRIPTION
**Pull request by Whyves**
…r. Behavior is on by default but can be turned off for performance.

### CODE REVIEW

**Comment by Whyves** [comment]
@stefanneculai,

I have wrapped the previous logic into an option. It is "on" by default to keep same behaviour but those having performance issues can turn it off.

I also think that the event handling mechanism should be refactored a little bit. Will try to tackle that when I have a bit of free time.

**Comment by stefanneculai** [comment]
We'd prefeer to have it false by default. High performance should be by default, not optional.

**Comment by stefanneculai** [comment]
Hi @Whyves! Could you please change **immediateModelUpdate** to **angularImmediateModelUpdate** and set the option to `false` by default? We'll make a new release shortly and would like to include these changes as well. Thank you.

**Comment by Whyves** [comment]
Hi @stefanneculai , Done but I renamed to immediateAngularModelUpdate ... makes more sense this way.

**Comment by stefanneculai** [comment]
:+1:

**Pull request merged**
