### PR TITLE
fix #164 content not shown until clicked with initOnClick set to true

### LINKED ISSUE #164: angular-froala does not show content before click when initOnClick set to true
I am using `angular-froala` with angular 1.5.x and came across the below issue.

I am initializing froala with `initOnClick `as `true`.
The problem is, it is not showing content before clicking.
If my variable given to `ng-model` is not empty then it should display the content and not placeholder.
Please find attached [punker](https://embed.plnkr.co/sWt9gy30rwOEulgPnQxS/)

**Example:**
If  `$scope.myHtml = "<p>Some text</p>";`

**Actual:**
Editor displays default placeholder before clicking.

**Expected:**
Editor should display "Some text" before clicking

### PR DESCRIPTION
**Pull request by Sgtfishtank**

### CODE REVIEW

**Comment by FWennerdahl** [comment]
This doesn't work as intended. The undo module isn't loaded when the "initializatioDelayed" event is fired, causing the call to "undo.reset" on line 77 to throw an error. We'll take another look at this and update.

**Comment by FWennerdahl** [comment]
Updated $render to delay resetting the undo history when until the editor is fully initialized when using initOnClick.

**Comment by stefanneculai** [comment]
Fixed in https://github.com/froala/angular-froala/commit/01bcc7d669eb2e9dc8f1ea2142ce671604762d4b.

**Comment by FWennerdahl** [comment]
@stefanneculai: With the fix in https://github.com/froala/angular-froala/commit/01bcc7d669eb2e9dc8f1ea2142ce671604762d4b, wont `ctrl.editorInitialized` still be set to `true` by `flushNgModel()` when the `'froalaEditor.initialized'` event is fired?

**Pull request closed without merging**
