### PR TITLE
Fix bower Font-Awesome

### PR DESCRIPTION
**Pull request by enkodellc**

### CODE REVIEW

**Comment by stefanneculai** [comment]
Not sure if we should do this because FroalaWysiwygEditor depends on FontAwesome.

**Comment by cgallarno** [comment]
Shouldn't FontAwesome come in with FroalaWysiwygEditor and not this Angular wrapper?

**Comment by stefanneculai** [comment]
@cgallarno That is right. I am closing this.

**Comment by enkodellc** [comment]
So should I submit a PR for FroalaWysiwygEditor to solve this issue? In any case this demo does not work and needs to be fixed.

**Comment by stefanneculai** [comment]
Indeed, FroalaWysiwygEditor from bower was missing Font Awesome dependency. I have updated that: https://github.com/froala/wysiwyg-editor/commit/36ef2eb5f873e95449be3aa051ce15304c09706f

**Comment by enkodellc** [comment]
Will you need to update the Index.html to point to the proper bower folder still as in my PR?

**Comment by stefanneculai** [comment]
Yes. Could you please update that?

**Comment by stefanneculai** [comment]
:+1:

**Pull request merged**
